// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.apex.ams.helloworld;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:first.demo.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>string note = 2;</code>
   */
  java.lang.String getNote();
  /**
   * <code>string note = 2;</code>
   */
  com.google.protobuf.ByteString
      getNoteBytes();

  /**
   * <code>int32 count = 3;</code>
   */
  int getCount();

  /**
   * <code>repeated .first.demo.Record records = 4;</code>
   */
  java.util.List<com.apex.ams.helloworld.Record> 
      getRecordsList();
  /**
   * <code>repeated .first.demo.Record records = 4;</code>
   */
  com.apex.ams.helloworld.Record getRecords(int index);
  /**
   * <code>repeated .first.demo.Record records = 4;</code>
   */
  int getRecordsCount();
  /**
   * <code>repeated .first.demo.Record records = 4;</code>
   */
  java.util.List<? extends com.apex.ams.helloworld.RecordOrBuilder> 
      getRecordsOrBuilderList();
  /**
   * <code>repeated .first.demo.Record records = 4;</code>
   */
  com.apex.ams.helloworld.RecordOrBuilder getRecordsOrBuilder(
      int index);
}
