// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.apex.ams.helloworld;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:first.demo.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string func = 1;</code>
   */
  java.lang.String getFunc();
  /**
   * <code>string func = 1;</code>
   */
  com.google.protobuf.ByteString
      getFuncBytes();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string header = 3;</code>
   */
  java.lang.String getHeader();
  /**
   * <code>string header = 3;</code>
   */
  com.google.protobuf.ByteString
      getHeaderBytes();

  /**
   * <code>string body = 4;</code>
   */
  java.lang.String getBody();
  /**
   * <code>string body = 4;</code>
   */
  com.google.protobuf.ByteString
      getBodyBytes();
}
