// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.apex.ams.helloworld;

public final class Helloworld {
  private Helloworld() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_first_demo_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_first_demo_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_first_demo_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_first_demo_HelloResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_first_demo_Record_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_first_demo_Record_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020helloworld.proto\022\nfirst.demo\"H\n\014HelloR" +
      "equest\022\014\n\004func\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\016\n\006he" +
      "ader\030\003 \001(\t\022\014\n\004body\030\004 \001(\t\"_\n\rHelloRespons" +
      "e\022\014\n\004code\030\001 \001(\005\022\014\n\004note\030\002 \001(\t\022\r\n\005count\030\003" +
      " \001(\005\022#\n\007records\030\004 \003(\0132\022.first.demo.Recor" +
      "d\"6\n\006Record\022\n\n\002id\030\001 \001(\005\022\017\n\007rowCode\030\002 \001(\t" +
      "\022\017\n\007rowName\030\003 \001(\t2Z\n\021HelloworldService\022E" +
      "\n\014firstService\022\030.first.demo.HelloRequest" +
      "\032\031.first.demo.HelloResponse\"\000B\033\n\027com.ape" +
      "x.ams.helloworldP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_first_demo_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_first_demo_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_first_demo_HelloRequest_descriptor,
        new java.lang.String[] { "Func", "Name", "Header", "Body", });
    internal_static_first_demo_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_first_demo_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_first_demo_HelloResponse_descriptor,
        new java.lang.String[] { "Code", "Note", "Count", "Records", });
    internal_static_first_demo_Record_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_first_demo_Record_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_first_demo_Record_descriptor,
        new java.lang.String[] { "Id", "RowCode", "RowName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
