// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.apex.ams.helloworld;

public interface RecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:first.demo.Record)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string rowCode = 2;</code>
   */
  java.lang.String getRowCode();
  /**
   * <code>string rowCode = 2;</code>
   */
  com.google.protobuf.ByteString
      getRowCodeBytes();

  /**
   * <code>string rowName = 3;</code>
   */
  java.lang.String getRowName();
  /**
   * <code>string rowName = 3;</code>
   */
  com.google.protobuf.ByteString
      getRowNameBytes();
}
